// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ReptiGram Firebase Configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiT-1kdubTNYLe2waeCIYvGDx5nakKyh0',
    appId: '1:373955522567:web:7163187c33d378455bbaa2',
    messagingSenderId: '373955522567',
    projectId: 'reptigramfirestore',
    authDomain: 'reptigramfirestore.firebaseapp.com',
    storageBucket: 'reptigramfirestore.firebasestorage.app',
    measurementId: 'G-H7FDWLXW64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiT-1kdubTNYLe2waeCIYvGDx5nakKyh0',
    appId: '1:373955522567:android:7163187c33d378455bbaa2',
    messagingSenderId: '373955522567',
    projectId: 'reptigramfirestore',
    storageBucket: 'reptigramfirestore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiT-1kdubTNYLe2waeCIYvGDx5nakKyh0',
    appId: '1:373955522567:ios:7163187c33d378455bbaa2',
    messagingSenderId: '373955522567',
    projectId: 'reptigramfirestore',
    storageBucket: 'reptigramfirestore.firebasestorage.app',
    iosBundleId: 'com.reptigram.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiT-1kdubTNYLe2waeCIYvGDx5nakKyh0',
    appId: '1:373955522567:macos:7163187c33d378455bbaa2',
    messagingSenderId: '373955522567',
    projectId: 'reptigramfirestore',
    storageBucket: 'reptigramfirestore.firebasestorage.app',
    iosBundleId: 'com.reptigram.app',
  );
} 